### ISSUE TITLE
The result of the searches does not match that of the downloaded records.

### ISSUE THREAD

**Issue by MatteoSid** [scrapfly/scrapfly-scrapers#1]
If I manually search for python in texas I found 5772 job offers but the script downloads only 2.

![image](https://github.com/scrapfly/scrapfly-scrapers/assets/26544399/312d7f80-1e14-4b55-b4e3-5b598c882c8c)

![image](https://github.com/scrapfly/scrapfly-scrapers/assets/26544399/9eae8678-edce-4751-9fc6-13c70b9ac3f8)

**Comment by Granitosaurus** [comment]
Hey @MatteoSid 
I couldn't replicate this issue which leads me to believe that you might be misunderstanding the `run.py` example file.

If you take a look at the code:
```python
    url = "https://www.indeed.com/jobs?q=python&l=Texas"
    result_search = await indeed.scrape_search(url, max_results=100)
    output.joinpath("search.json").write_text(json.dumps(result_search, indent=2, ensure_ascii=False))

    jobs = ["4c1e2988b22fa223", "483d39cbe1b6c1fe"]
    result_jobs = await indeed.scrape_jobs(jobs)
    output.joinpath("jobs.json").write_text(json.dumps(result_jobs, indent=2, ensure_ascii=False))
```

This example scrapes search for the first 100 job listing preview results (see `/results/search.json` for example output) and then scrapes 2 invidual jobs for full job listing details (see `/results/jobs.json` for example output).

You can modify this to your needs to scrape more search results and turn job previews to full job datasets (see the `jobKey` field in the job preview item). 
Hopefully that solves your issue!
