### ISSUE TITLE
Instagram-scraper (Phone/Mail = Null)

### ISSUE THREAD

**Issue by ChristianBdv** [scrapfly/scrapfly-scrapers#21]
**Scraper**
Which scraper is affected? Instagram-Scraper
**Environment**
Python version: use `python --version`3.11.8
Operating System: Kali
**Describe the bug**

FOR EDUCATIONAL TEST

I wanted to test instagram-scraper on a profile where there is a phone number and an email (Information I could get with the IGEmail extension of chrome ) by scraping the followers of a first profile.
[Line 14 of File : IGEmail_elsanidiakelly_25_followers.csv]
[IGEmail_elsanidiakelly_25_followers.csv](https://github.com/user-attachments/files/15540219/IGEmail_elsanidiakelly_25_followers.csv)

The profile in which the phone number and email are located has "null" values in the user.json file.
I don’t understand why these two values are not present in the user.json (Joint) file
[user.json](https://github.com/user-attachments/files/15540228/user.json)

Thanks for your help

**Comment by ChristianBdv** [comment]
Johann vous pouvez me faire une réponse en Français
Merci

**Comment by Granitosaurus** [comment]
I don't see any phone number or email details in the public profile mentioned in `user.json` file. We only support scraping of public data fields with our instagram-scraper reference code. 

Closing this but if you could clarify if the data is available somewhere publicly we can take another look at this.

**Comment by ChristianBdv** [comment]
Thank you for your prompt response !!

I'm a little frustrated, because when I connect to the elsanidiakelly account and I scrape the followers with the IGEmail Chrome extension which requires no API or installation. Different profiles appear with phone number and email. This is why I wanted to test your instagram-scraper script and it does not recover the information. This information is public since it is a follower, I have not carried out any manipulation to make private information!!
I'm totally surprised...
See for yourself why such a difference!!
Sorry to insist!! I am a trainer for investigation and it is very important to have this type of information.
Thank you for the follow-up
Sincerely

**Comment by Granitosaurus** [comment]
Hey @ChristianBdv the definition of public and private can be a bit different in web scraping context. Generally, if you need to login to view the information it's _not_ public, meaning we cannot assist or tutor you how to scrape it as this gets into complicated legal areas of data acquisition as by logging in you explicitly agree with Instagram's terms of service that forbid automated scraping. 

It might be different legally for your situation but as far as this educational repository goes we can't assist you with scraping these details with the way Instagram works currently. Hope that clarifies some things!

**Comment by ChristianBdv** [comment]
Thank you Granitosaurus

Your answer is very clear! With a law degree, I understand very well this notion of public/private and the general conditions of Instagram.
My audience, due to their function, has a single objective: to retrieve information to optimize investigations.
Good luck with Scrapfly
