### ISSUE TITLE
instagram-scraper doesn't work as exepected.

### ISSUE THREAD

**Issue by quroom** [scrapfly/scrapfly-scrapers#22]
**Scraper**
Which scraper is affected?
instagram-scraper

**Environment**
Python version: use `python --version`
3.10.14
Scrapfly SDK version: use `pip show scrapfly-sdk`
0.817
Operating System: Windows, Linux, Macos
wsl

**Describe the bug**
A clear and concise description of what the bug is and how the scrape command is being ran?
When I run instagram-scraper same code , all-user-posts.json empty.

**Received Output**
Data produced by the scraper
empy posts!

**Expected Output**
What data is wanted
Should write posts to all-user-posts.

**Screenshots**
![image](https://github.com/user-attachments/assets/e018130d-d70b-4604-9975-405f0301f508)
The log tells user scaping 2472 posts.
But When I check all-user-posts.json file, it's like this.. empty
![image](https://github.com/user-attachments/assets/2137efcd-790c-470e-b78c-6a28d0b650a9)

**Additional context**

I am considering that I move apify to scrapfly for instagram and facebook scraper.
But I am not sure this is reliable.

**Comment by mazen-r** [comment]
Hey @quroom, thanks for mentioning this. The `page_size` was greater than the maximum limit allowed, and hence empty results were retrieved. The instagram-scraper It has been updated.

**Comment by quroom** [comment]
> Hey @quroom, thanks for mentioning this. The `page_size` was greater than the maximum limit allowed, and hence empty results were retrieved. The instagram-scraper It has been updated.

Thanks for fast response. I will check it tmr.

**Comment by quroom** [comment]
> Hey @quroom, thanks for mentioning this. The `page_size` was greater than the maximum limit allowed, and hence empty results were retrieved. The instagram-scraper It has been updated.

It works very well now.
I have some suggestions to improve scrapfly admin page.
And pricing page.
When I am done summarizing , can I make a issue for that?
Or email is better?

**Comment by mazen-r** [comment]
Yes @quroom, please send us an email at support@scrapfly.io
