### ISSUE TITLE
error in function parse_hidden_data

### ISSUE THREAD

**Issue by DungNguyen83** [scrapfly/scrapfly-scrapers#25]
selector = response.selector
AttributeError: 'ScrapflyAspError' object has no attribute 'selector'

**Comment by mazen-r** [comment]
Hello @DungNguyen83, which scraper have you run to get this error? This isn't a bug. This error is thrown when the request is blocked with a `ScrapflyAspError`, see related [error docs](https://scrapfly.io/docs/scrape-api/errors#asp). The scraper where this error is thrown doesn't have the required error handling logic to tolerate such a case, accessing the selector before checking for scrape failures.

**Comment by mazen-r** [comment]
closed due to inactivity.
