### ISSUE TITLE
The tiktok scraper failed to scrape comments

### ISSUE THREAD

**Issue by hmtrii** [scrapfly/scrapfly-scrapers#26]
**Scraper**
Which scraper is affected?
Tiktok-scraper
**Environment**
Python version: use `python --version`
3.9.17
Scrapfly SDK version: use `pip show scrapfly-sdk`
0.8.18
Operating System: Windows, Linux, Macos
Linux
**Describe the bug**
A clear and concise description of what the bug is and how the scrape command is being ran?
I scrape tiktok comments following the _How To Scrape TikTok Comments?_ part in this tutorial: [link](https://scrapfly.io/blog/how-to-scrape-tiktok-python-json/#how-to-scrape-tiktok-comments)
And I face this bug:
```
Traceback (most recent call last):
  File "path/to/file", line 111, in <module>
    asyncio.run(run())
  File ".../lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "path/to/file", line 97, in run
    comment_data = await scrape_comments(
  File "path/to/file", line 63, in scrape_comments
    data = parse_comments(first_page)
  File "path/to/file", line 15, in parse_comments
    comments_data = data["comments"]
KeyError: 'comments'
```

**Received Output**
Data produced by the scraper
**Expected Output**
What data is wanted
**Screenshots**
**Additional context**
The tiktok comment api may be need more params to return response correctly.
Using 3 params same in the tutorial (```aweme_id, count, cursor```), the response is: 
`{"log_pb":{"impr_id":"20241018080908C5EF9FB7627D8000C966"},"status_code":5,"status_msg":""}`
This leads the error.

**Comment by mazen-r** [comment]
Hey @hmtrii , thanks for reporting this! The comments API now requires specific URL parameters to authorize the calls. We have updated our TikTok scraper accordingly and it should be working again.
