### ISSUE TITLE
The tiktok scraper failed to scrape posts from a channel

### ISSUE THREAD

**Issue by elonge** [scrapfly/scrapfly-scrapers#28]
**Scraper**
Which scraper is affected? 
Tiktok
**Environment**
Python version: use `python --version`
Python 3.12.3
Scrapfly SDK version: use `pip show scrapfly-sdk`
Name: scrapfly-sdk
Version: 0.8.18
Summary: Scrapfly SDK for Scrapfly
Home-page: https://github.com/scrapfly/python-sdk
Author: Scrapfly
Author-email: tech@scrapfly.io
License: BSD
Location: /Users/elongecht/code/onecut-server/onecut-service/.venv/lib/python3.12/site-packages
Requires: backoff, decorator, loguru, python-dateutil, requests, urllib3
Required-by: 
Operating System: Windows, Linux, Macos
Macos
**Describe the bug**
The scrape_channel function always return 0 posts, even if the tiktok profile has posts.
A clear and concise description of what the bug is and how the scrape command is being ran?
I'm running the tiktok scraper using the run.py from the git. Instead of getting a list of posts, I'm always getting 0 posts. This also happens on the test user (@oddanimalspecimens) or any other user.
**Received Output**
When using the run.py in the git, the channel.json result is empty list ([])
**Expected Output**
A list of video posts made by the test user
**Screenshots**
**Additional context**
I used the updated code from Oct. 24. When running the older version, the results are the same.

**Comment by mazen-r** [comment]
Hey @elonge, thanks for reporting this. We are taking a look.

**Comment by mazen-r** [comment]
Hey @elonge, the issue is resolved. You should be able to retrieve channel posts.
