### ISSUE TITLE
clips_music_attribution_info is always null

### ISSUE THREAD

**Issue by orenc-onecut** [scrapfly/scrapfly-scrapers#29]
**Scraper**
ScrapflyClient -> instagram-scraper

**Environment**
Python 3.11.6
scrapfly-sdk 0.8.19
MacOS

**Describe the bug**
The clips_music_attribution_info field (per video) is always null, is there a way to scrape the song name (and details)?

**Received Output**
null

**Expected Output**
e.g. for video https://www.instagram.com/p/DCy_NAgphU7/ I'd like to get: "Kelly Clarkson" + "Sleigh Ride"

**Comment by mazen-r** [comment]
Hey @orenc-onecut, the music data exists under the `music` key, it's renamed from its original key `clips_music_attribution_info`:
```json
  "music": {
    "artist_name": "Kelly Clarkson",
    "song_name": "Sleigh Ride",
    "uses_original_audio": false,
    "should_mute_audio": false,
    "should_mute_audio_reason": "",
    "audio_id": "2722867441232706"
  },
```
